/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/settings/AboutSection.vue')['default']
    AddBookDialog: typeof import('./components/books/AddBookDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BookDetailDialog: typeof import('./components/books/BookDetailDialog.vue')['default']
    BookList: typeof import('./components/books/BookList.vue')['default']
    DataManagement: typeof import('./components/settings/DataManagement.vue')['default']
    DeleteBookDialog: typeof import('./components/books/DeleteBookDialog.vue')['default']
    EditBookDialog: typeof import('./components/books/EditBookDialog.vue')['default']
    ErrorMessage: typeof import('./components/global/ErrorMessage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NotificationSettings: typeof import('./components/settings/NotificationSettings.vue')['default']
    ProfileSettings: typeof import('./components/settings/ProfileSettings.vue')['default']
    RatingDistribution: typeof import('./components/analytics/RatingDistribution.vue')['default']
    ReadingPreferences: typeof import('./components/settings/ReadingPreferences.vue')['default']
    ReadingTimeline: typeof import('./components/analytics/ReadingTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./components/analytics/StatsCard.vue')['default']
    TopAuthors: typeof import('./components/analytics/TopAuthors.vue')['default']
  }
}
